%YAML 1.1
---
init:
  require:
    - ...
    - ...

routes:
  - '/':
      handler: modperl
      handlers:
        PerlAccessHandler:   ['...']
        PerlResponseHandler: ['...']
      access:
        order: [deny, allow]
        default: allow

  - '/edit':
      handler: modperl
      handlers:
        PerlAccessHandler:   ['...']
        PerlResponseHandler: ['..']
      access:
        order: [deny, allow]
        default: allow
