%YAML 1.1
---
- '/':
    handler: modperl
    handlers:
      PerlAccessHandler:   ['...']
      PerlResponseHandler: ['...']
    access:
      order: [deny, allow]
      default: allow

- '/edit':
    handler: modperl
    handlers:
      PerlAccessHandler:   ['...']
      PerlResponseHandler: ['..']
    access:
      order: [deny, allow]
      default: allow
